import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation objects
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.groups': 'Groups',
    'nav.calendar': 'Calendar',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.join': 'Join',
    'common.leave': 'Leave',
    'common.send': 'Send',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.settings': 'Settings',
    
    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.language': 'Language',
    'profile.english': 'English',
    'profile.spanish': 'Spanish',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.birthDate': 'Birth Date',
    'profile.country': 'Country',
    'profile.editProfile': 'Edit Profile',
    'profile.eventsOrganized': 'Events Organized',
    'profile.groupsJoined': 'Groups Joined',
    'profile.messagesSent': 'Messages Sent',
    'profile.notifications': 'Notifications',
    'profile.notificationsDesc': 'Manage notification settings',
    'profile.privacy': 'Privacy & Security',
    'profile.privacyDesc': 'Control your privacy settings',
    'profile.help': 'Help & Support',
    'profile.helpDesc': 'Get help and contact support',
    'profile.appVersion': 'Making group planning simple and fun',
    'profile.signOut': 'Sign Out',
    'profile.close': 'Close',
    'profile.done': 'Done',
    'profile.uploadNew': 'Upload new',
    'profile.uploading': 'Uploading...',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome back',
    'auth.getStarted': 'Get Started',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.username': 'Username',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.birthDate': 'Birth Date',
    'auth.country': 'Country',
    'auth.chooseUsername': 'Choose a unique username',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.usernameAvailable': 'Username is available',
    'auth.usernameTaken': 'Username is already taken',
    'auth.alreadyAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.selectCountry': 'Select your country',
    
    // Groups
    'groups.title': 'Groups',
    'groups.recent': 'Recent Groups',
    'groups.createGroup': 'Create Group',
    'groups.joinGroup': 'Join Group',
    'groups.members': 'members',
    'groups.admin': 'admin',
    'groups.noGroups': 'No groups yet',
    'groups.noGroupsDescription': 'Create or join a group to start planning with friends!',
    'groups.enterInviteCode': 'Enter invite code',
    'groups.pleaseEnterValidCode': 'Please enter a valid invite code',
    'groups.joinedGroup': 'Joined group!',
    'groups.successfullyJoined': 'You\'ve successfully joined the group',
    'groups.failedToJoinGroup': 'Failed to join group',
    'groups.invalidInviteCode': 'Invalid invite code',
    'groups.joinGroupPlaceholder': 'Enter invite code...',
    'groups.joining': 'Joining...',
    'groups.join': 'Join',
    'groups.loadingGroups': 'Loading groups...',
    'groups.leftGroup': 'Left group',
    'groups.couldNotLeaveGroup': 'Could not leave group',
    'groups.share': 'Share',
    'groups.leave': 'Leave',
    'groups.leaving': 'Leaving...',
    'groups.inviteLinkCopied': 'Invite link copied',
    'groups.shareWithFriends': 'Share it with your friends to join the group.',
    'groups.unableToShare': 'Unable to share',
    'groups.copyCodeManually': 'Please copy the code manually.',
    'groups.code': 'Code:',
    
    // Dashboard
    'dashboard.recentGroups': 'Recent Groups',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.viewAll': 'View all',
    'dashboard.noUpcomingEvents': 'No upcoming events',
    'dashboard.noUpcomingDescription': 'Proposals appear here when they are scheduled with a date.',
    'dashboard.viewCalendar': 'View Calendar',
    
    // Welcome
    'welcome.tagline': 'The easiest way to organize plans with friends. Create proposals, vote together, and turn decisions into memories.',
    'welcome.getStarted': 'Get Started',
    'welcome.signIn': 'Sign In',
    'welcome.howItWorks': 'How it works',
    'welcome.createGroups': 'Create Groups',
    'welcome.createGroupsDesc': 'Easily invite friends with simple codes',
    'welcome.makeProposals': 'Make Proposals',
    'welcome.makeProposalsDesc': 'Suggest dates, activities, and times',
    'welcome.chatVote': 'Chat & Vote',
    'welcome.chatVoteDesc': 'Discuss and vote on the best options',
    'welcome.planTogether': 'Plan Together',
    'welcome.planTogetherDesc': 'Turn decisions into confirmed events',
    'welcome.joinThousands': 'Join thousands planning better together',
    
    // Chat
    'chat.title': 'Chats',
    'chat.noMessages': 'No messages yet',
    'chat.startConversation': 'Start the conversation!',
    'chat.typeMessage': 'Type a message...',
    'chat.groupChat': 'Group chat',
    'chat.noChats': 'No chats yet',
    'chat.noChatsDescription': 'Join or create groups to start chatting with others!',
    'chat.viewGroups': 'View Groups',
    'chat.loadingMessages': 'Loading messages...',
    'chat.noMessagesYet': 'No messages yet',
    'chat.failedToSend': 'Failed to send message',
    'chat.somethingWrong': 'Something went wrong',
    
    // Auth
    'auth.welcomeBack': 'Welcome back',
    'auth.createAccount': 'Create account',
    'auth.username': 'Username',
    'auth.usernamePlaceholder': 'Choose a unique username',
    'auth.firstName': 'First Name',
    'auth.firstNamePlaceholder': 'First name',
    'auth.lastName': 'Last Name',
    'auth.lastNamePlaceholder': 'Last name',
    'auth.birthDate': 'Birth Date',
    'auth.country': 'Country',
    'auth.selectCountry': 'Select your country',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign up',
    'auth.loading': 'Loading...',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.usernameUnavailable': 'Username is already taken',
    'auth.usernameAvailable': 'Username is available',
    'auth.errorSigningIn': 'Error signing in',
    'auth.passwordsDontMatch': "Passwords don't match",
    'auth.passwordsMatchError': 'Please make sure your passwords match',
    'auth.errorCreatingAccount': 'Error creating account',
    'auth.accountCreated': 'Account created!',
    'auth.checkEmailVerify': 'Please check your email to verify your account',
    
    // Create Group
    'createGroup.title': 'Create Group',
    'createGroup.groupNameRequired': 'Group name required',
    'createGroup.enterGroupName': 'Please enter a name for your group',
    'createGroup.imageUploadFailed': 'Image upload failed',
    'createGroup.failedToSetImage': 'Failed to set group image',
    'createGroup.groupCreated': 'Group created!',
    'createGroup.groupCreatedDesc': 'Your group "{name}" has been created successfully',
    'createGroup.failedToCreate': 'Failed to create group',
    'createGroup.changePhoto': 'Change Photo',
    'createGroup.addPhoto': 'Add Group Photo',
    'createGroup.groupName': 'Group Name',
    'createGroup.groupNamePlaceholder': 'e.g., Weekend Squad',
    'createGroup.description': 'Description',
    'createGroup.descriptionPlaceholder': 'What\'s this group about?',
    'createGroup.creating': 'Creating...',
    'createGroup.create': 'Create Group',
    'createGroup.quickTips': '💡 Quick Tips',
    'createGroup.tip1': 'Choose a memorable name for your group',
    'createGroup.tip2': 'An invite code will be automatically generated',
    'createGroup.tip3': 'You can change settings later in group preferences',
    
    // Create Proposal
    'createProposal.title': 'Create Proposal',
    'createProposal.createNew': 'Create New Proposal',
    'createProposal.missingFields': 'Missing required fields',
    'createProposal.enterTitle': 'Please enter a title',
    'createProposal.proposalCreated': 'Proposal created!',
    'createProposal.openForVoting': '"{title}" is now open for voting',
    'createProposal.failedToCreate': 'Failed to create proposal',
    'createProposal.proposalTitle': 'Proposal Title',
    'createProposal.titlePlaceholder': 'e.g., Should we go to the beach this weekend?',
    'createProposal.description': 'Description',
    'createProposal.descriptionPlaceholder': 'Provide more details about your proposal...',
    'createProposal.votingDeadline': 'Voting Deadline (Optional)',
    'createProposal.eventDate': 'Event Date (If proposal becomes an event)',
    'createProposal.location': 'Location (Optional)',
    'createProposal.locationPlaceholder': 'e.g., Central Park, New York',
    'createProposal.image': 'Image (Optional)',
    'createProposal.cancel': 'Cancel',
    'createProposal.creating': 'Creating...',
    'createProposal.create': 'Create Proposal',
    
    // Join Group
    'joinGroup.title': 'Join Group',
    'joinGroup.joinedGroup': 'Joined group!',
    'joinGroup.welcomeToGroup': 'Welcome to your new group.',
    'joinGroup.failedToJoin': 'Failed to join group',
    'joinGroup.loadingInvite': 'Loading invite…',
    'joinGroup.invitedToJoin': 'You\'re invited to join {groupName}',
    'joinGroup.invitedGeneric': 'You\'re invited to join a group',
    'joinGroup.chooseContinue': 'Choose how you want to continue',
    'joinGroup.haveAccount': 'I already have an account',
    'joinGroup.createAccount': 'Create an account',
    'joinGroup.autoJoin': 'After you login or sign up, we\'ll join you to the group automatically.',
    'joinGroup.processingInvite': 'Processing your invite…',
    
    // Group Management
    'groupMgmt.title': 'Group Management',
    'groupMgmt.groupUpdated': 'Group updated',
    'groupMgmt.groupSaved': 'Group information has been saved',
    'groupMgmt.failedToUpdate': 'Failed to update group',
    'groupMgmt.memberRemoved': 'Member removed',
    'groupMgmt.memberRemovedDesc': 'The member has been removed from the group',
    'groupMgmt.failedToRemove': 'Failed to remove member',
    'groupMgmt.memberPromoted': 'Member promoted',
    'groupMgmt.memberPromotedDesc': 'The member has been promoted to admin',
    'groupMgmt.failedToPromote': 'Failed to promote member',
    'groupMgmt.groupImageUpdated': 'Group image updated',
    'groupMgmt.failedToUpdateImage': 'Failed to update image',
    'groupMgmt.confirmDelete': 'Are you sure you want to delete this group? This action cannot be undone.',
    'groupMgmt.groupDeleted': 'Group deleted',
    'groupMgmt.failedToDelete': 'Failed to delete group',
    'groupMgmt.groupNotFound': 'Group Not Found',
    'groupMgmt.noAccess': 'This group doesn\'t exist or you don\'t have access to it.',
    'groupMgmt.backToGroups': 'Back to Groups',
    'groupMgmt.accessDenied': 'Access Denied',
    'groupMgmt.needAdmin': 'You need admin privileges to manage this group.',
    'groupMgmt.backToGroup': 'Back to Group',
    'groupMgmt.edit': 'Edit',
    'groupMgmt.uploading': 'Uploading...',
    'groupMgmt.inviteCode': 'Invite Code:',
    'groupMgmt.members': 'Members',
    'groupMgmt.admin': 'Admin',
    'groupMgmt.joined': 'Joined',
    'groupMgmt.promote': 'Promote',
    'groupMgmt.dangerZone': 'Danger Zone',
    'groupMgmt.deleteWarning': 'Deleting a group will remove all its content.',
    'groupMgmt.deleteGroup': 'Delete Group',
    'groupMgmt.editGroup': 'Edit Group',
    'groupMgmt.groupName': 'Group Name',
    'groupMgmt.groupNamePlaceholder': 'Enter group name',
    'groupMgmt.description': 'Description',
    'groupMgmt.descriptionPlaceholder': 'Enter group description',
    'groupMgmt.cancel': 'Cancel',
    'groupMgmt.saveChanges': 'Save Changes',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.groups': 'Grupos',
    'nav.calendar': 'Calendario',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.join': 'Unirse',
    'common.leave': 'Salir',
    'common.send': 'Enviar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.settings': 'Configuración',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.language': 'Idioma',
    'profile.english': 'Inglés',
    'profile.spanish': 'Español',
    'profile.username': 'Nombre de usuario',
    'profile.email': 'Correo electrónico',
    'profile.firstName': 'Nombre',
    'profile.lastName': 'Apellidos',
    'profile.birthDate': 'Fecha de nacimiento',
    'profile.country': 'País',
    'profile.editProfile': 'Editar Perfil',
    'profile.eventsOrganized': 'Eventos Organizados',
    'profile.groupsJoined': 'Grupos Unidos',
    'profile.messagesSent': 'Mensajes Enviados',
    'profile.notifications': 'Notificaciones',
    'profile.notificationsDesc': 'Gestionar configuración de notificaciones',
    'profile.privacy': 'Privacidad y Seguridad',
    'profile.privacyDesc': 'Controlar tu configuración de privacidad',
    'profile.help': 'Ayuda y Soporte',
    'profile.helpDesc': 'Obtener ayuda y contactar con el soporte',
    'profile.appVersion': 'Hacer que planificar en grupo sea sencillo y divertido',
    'profile.signOut': 'Cerrar Sesión',
    'profile.close': 'Cerrar',
    'profile.done': 'Hecho',
    'profile.uploadNew': 'Subir nuevo',
    'profile.uploading': 'Subiendo...',
    
    // Auth
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.createAccount': 'Crear Cuenta',
    'auth.welcomeBack': 'Bienvenido de vuelta',
    'auth.getStarted': 'Comenzar',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.username': 'Usuario',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.birthDate': 'Fecha de nacimiento',
    'auth.country': 'País',
    'auth.chooseUsername': 'Elige un nombre de usuario único',
    'auth.enterEmail': 'Ingresa tu correo',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'auth.usernameAvailable': 'Nombre de usuario disponible',
    'auth.usernameTaken': 'El nombre de usuario ya está tomado',
    'auth.alreadyAccount': '¿Ya tienes una cuenta?',
    'auth.noAccount': '¿No tienes una cuenta?',
    'auth.selectCountry': 'Selecciona tu país',
    
    // Groups
    'groups.title': 'Grupos',
    'groups.recent': 'Grupos Recientes',
    'groups.createGroup': 'Crear Grupo',
    'groups.joinGroup': 'Unirse a Grupo',
    'groups.members': 'miembros',
    'groups.admin': 'admin',
    'groups.noGroups': 'Sin grupos aún',
    'groups.noGroupsDescription': '¡Crea o únete a un grupo para empezar a planificar con amigos!',
    'groups.enterInviteCode': 'Introduce el código de invitación',
    'groups.pleaseEnterValidCode': 'Por favor introduce un código de invitación válido',
    'groups.joinedGroup': '¡Te has unido al grupo!',
    'groups.successfullyJoined': 'Te has unido correctamente al grupo',
    'groups.failedToJoinGroup': 'Error al unirse al grupo',
    'groups.invalidInviteCode': 'Código de invitación inválido',
    'groups.joinGroupPlaceholder': 'Introduce el código de invitación...',
    'groups.joining': 'Uniéndose...',
    'groups.join': 'Unirse',
    'groups.loadingGroups': 'Cargando grupos...',
    'groups.leftGroup': 'Has salido del grupo',
    'groups.couldNotLeaveGroup': 'No se ha podido salir del grupo',
    'groups.share': 'Compartir',
    'groups.leave': 'Salir',
    'groups.leaving': 'Saliendo...',
    'groups.inviteLinkCopied': 'Enlace de invitación copiado',
    'groups.shareWithFriends': 'Compártelo con tus amigos para que se unan al grupo.',
    'groups.unableToShare': 'No se puede compartir',
    'groups.copyCodeManually': 'Por favor copia el código manualmente.',
    'groups.code': 'Código:',
    
    // Dashboard
    'dashboard.recentGroups': 'Grupos Recientes',
    'dashboard.upcomingEvents': 'Próximos Eventos',
    'dashboard.viewAll': 'Ver todo',
    'dashboard.noUpcomingEvents': 'No hay eventos próximos',
    'dashboard.noUpcomingDescription': 'Las propuestas aparecen aquí cuando se programan con una fecha.',
    'dashboard.viewCalendar': 'Ver Calendario',
    
    // Welcome
    'welcome.tagline': 'La forma más fácil de organizar planes con amigos. Cread propuestas, votad juntos, y convertid decisiones en recuerdos.',
    'welcome.getStarted': 'Comenzar',
    'welcome.signIn': 'Iniciar Sesión',
    'welcome.howItWorks': 'Cómo funciona',
    'welcome.createGroups': 'Crear Grupos',
    'welcome.createGroupsDesc': 'Invitad fácilmente a amigos con códigos sencillos',
    'welcome.makeProposals': 'Hacer Propuestas',
    'welcome.makeProposalsDesc': 'Sugerid fechas, actividades y horarios',
    'welcome.chatVote': 'Chatear y Votar',
    'welcome.chatVoteDesc': 'Discutid y votad por las mejores opciones',
    'welcome.planTogether': 'Planificar Juntos',
    'welcome.planTogetherDesc': 'Convertid decisiones en eventos confirmados',
    'welcome.joinThousands': 'Únete a miles planificando mejor juntos',
    
    // Chat
    'chat.title': 'Chats',
    'chat.noMessages': 'No hay mensajes aún',
    'chat.startConversation': '¡Inicia la conversación!',
    'chat.typeMessage': 'Escribe un mensaje...',
    'chat.groupChat': 'Chat grupal',
    'chat.noChats': 'No hay chats aún',
    'chat.noChatsDescription': '¡Únete o crea grupos para empezar a chatear con otros!',
    'chat.viewGroups': 'Ver Grupos',
    'chat.loadingMessages': 'Cargando mensajes...',
    'chat.noMessagesYet': 'No hay mensajes aún',
    'chat.failedToSend': 'Error al enviar mensaje',
    'chat.somethingWrong': 'Algo salió mal',
    
    // Auth
    'auth.welcomeBack': 'Bienvenido de nuevo',
    'auth.createAccount': 'Crear cuenta',
    'auth.username': 'Nombre de usuario',
    'auth.usernamePlaceholder': 'Elige un nombre de usuario único',
    'auth.firstName': 'Nombre',
    'auth.firstNamePlaceholder': 'Nombre',
    'auth.lastName': 'Apellidos',
    'auth.lastNamePlaceholder': 'Apellidos',
    'auth.birthDate': 'Fecha de nacimiento',
    'auth.country': 'País',
    'auth.selectCountry': 'Selecciona tu país',
    'auth.email': 'Correo electrónico',
    'auth.emailPlaceholder': 'Introduce tu correo electrónico',
    'auth.password': 'Contraseña',
    'auth.passwordPlaceholder': 'Introduce tu contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'auth.signIn': 'Iniciar sesión',
    'auth.signUp': 'Registrarse',
    'auth.loading': 'Cargando...',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.usernameUnavailable': 'El nombre de usuario ya está en uso',
    'auth.usernameAvailable': 'Nombre de usuario disponible',
    'auth.errorSigningIn': 'Error al iniciar sesión',
    'auth.passwordsDontMatch': 'Las contraseñas no coinciden',
    'auth.passwordsMatchError': 'Asegúrate de que las contraseñas coinciden',
    'auth.errorCreatingAccount': 'Error al crear la cuenta',
    'auth.accountCreated': '¡Cuenta creada!',
    'auth.checkEmailVerify': 'Revisa tu correo electrónico para verificar tu cuenta',
    
    // Create Group
    'createGroup.title': 'Crear Grupo',
    'createGroup.groupNameRequired': 'Nombre de grupo requerido',
    'createGroup.enterGroupName': 'Por favor introduce un nombre para tu grupo',
    'createGroup.imageUploadFailed': 'Error al subir la imagen',
    'createGroup.failedToSetImage': 'Error al establecer la imagen del grupo',
    'createGroup.groupCreated': '¡Grupo creado!',
    'createGroup.groupCreatedDesc': 'Tu grupo "{name}" ha sido creado correctamente',
    'createGroup.failedToCreate': 'Error al crear el grupo',
    'createGroup.changePhoto': 'Cambiar Foto',
    'createGroup.addPhoto': 'Añadir Foto del Grupo',
    'createGroup.groupName': 'Nombre del Grupo',
    'createGroup.groupNamePlaceholder': 'ej., Cuadrilla de Fin de Semana',
    'createGroup.description': 'Descripción',
    'createGroup.descriptionPlaceholder': '¿De qué trata este grupo?',
    'createGroup.creating': 'Creando...',
    'createGroup.create': 'Crear Grupo',
    'createGroup.quickTips': '💡 Consejos Rápidos',
    'createGroup.tip1': 'Elige un nombre memorable para tu grupo',
    'createGroup.tip2': 'Se generará automáticamente un código de invitación',
    'createGroup.tip3': 'Puedes cambiar la configuración más tarde en las preferencias del grupo',
    
    // Create Proposal
    'createProposal.title': 'Crear Propuesta',
    'createProposal.createNew': 'Crear Nueva Propuesta',
    'createProposal.missingFields': 'Faltan campos requeridos',
    'createProposal.enterTitle': 'Por favor introduce un título',
    'createProposal.proposalCreated': '¡Propuesta creada!',
    'createProposal.openForVoting': '"{title}" ya está abierta para votación',
    'createProposal.failedToCreate': 'Error al crear la propuesta',
    'createProposal.proposalTitle': 'Título de la Propuesta',
    'createProposal.titlePlaceholder': 'ej., ¿Deberíamos ir a la playa este fin de semana?',
    'createProposal.description': 'Descripción',
    'createProposal.descriptionPlaceholder': 'Proporciona más detalles sobre tu propuesta...',
    'createProposal.votingDeadline': 'Fecha Límite de Votación (Opcional)',
    'createProposal.eventDate': 'Fecha del Evento (Si la propuesta se convierte en evento)',
    'createProposal.location': 'Ubicación (Opcional)',
    'createProposal.locationPlaceholder': 'ej., Parque del Retiro, Madrid',
    'createProposal.image': 'Imagen (Opcional)',
    'createProposal.cancel': 'Cancelar',
    'createProposal.creating': 'Creando...',
    'createProposal.create': 'Crear Propuesta',
    
    // Join Group
    'joinGroup.title': 'Unirse al Grupo',
    'joinGroup.joinedGroup': '¡Te has unido al grupo!',
    'joinGroup.welcomeToGroup': 'Bienvenido a tu nuevo grupo.',
    'joinGroup.failedToJoin': 'Error al unirse al grupo',
    'joinGroup.loadingInvite': 'Cargando invitación…',
    'joinGroup.invitedToJoin': 'Estás invitado a unirte a {groupName}',
    'joinGroup.invitedGeneric': 'Estás invitado a unirte a un grupo',
    'joinGroup.chooseContinue': 'Elige cómo quieres continuar',
    'joinGroup.haveAccount': 'Ya tengo una cuenta',
    'joinGroup.createAccount': 'Crear una cuenta',
    'joinGroup.autoJoin': 'Después de iniciar sesión o registrarte, te uniremos al grupo automáticamente.',
    'joinGroup.processingInvite': 'Procesando tu invitación…',
    
    // Group Management
    'groupMgmt.title': 'Gestión del Grupo',
    'groupMgmt.groupUpdated': 'Grupo actualizado',
    'groupMgmt.groupSaved': 'La información del grupo ha sido guardada',
    'groupMgmt.failedToUpdate': 'Error al actualizar el grupo',
    'groupMgmt.memberRemoved': 'Miembro eliminado',
    'groupMgmt.memberRemovedDesc': 'El miembro ha sido eliminado del grupo',
    'groupMgmt.failedToRemove': 'Error al eliminar miembro',
    'groupMgmt.memberPromoted': 'Miembro promovido',
    'groupMgmt.memberPromotedDesc': 'El miembro ha sido promovido a administrador',
    'groupMgmt.failedToPromote': 'Error al promover miembro',
    'groupMgmt.groupImageUpdated': 'Imagen del grupo actualizada',
    'groupMgmt.failedToUpdateImage': 'Error al actualizar la imagen',
    'groupMgmt.confirmDelete': '¿Estás seguro de que quieres eliminar este grupo? Esta acción no se puede deshacer.',
    'groupMgmt.groupDeleted': 'Grupo eliminado',
    'groupMgmt.failedToDelete': 'Error al eliminar el grupo',
    'groupMgmt.groupNotFound': 'Grupo No Encontrado',
    'groupMgmt.noAccess': 'Este grupo no existe o no tienes acceso a él.',
    'groupMgmt.backToGroups': 'Volver a Grupos',
    'groupMgmt.accessDenied': 'Acceso Denegado',
    'groupMgmt.needAdmin': 'Necesitas privilegios de administrador para gestionar este grupo.',
    'groupMgmt.backToGroup': 'Volver al Grupo',
    'groupMgmt.edit': 'Editar',
    'groupMgmt.uploading': 'Subiendo...',
    'groupMgmt.inviteCode': 'Código de Invitación:',
    'groupMgmt.members': 'Miembros',
    'groupMgmt.admin': 'Administrador',
    'groupMgmt.joined': 'Se unió',
    'groupMgmt.promote': 'Promover',
    'groupMgmt.dangerZone': 'Zona Peligrosa',
    'groupMgmt.deleteWarning': 'Eliminar un grupo eliminará todo su contenido.',
    'groupMgmt.deleteGroup': 'Eliminar Grupo',
    'groupMgmt.editGroup': 'Editar Grupo',
    'groupMgmt.groupName': 'Nombre del Grupo',
    'groupMgmt.groupNamePlaceholder': 'Introduce el nombre del grupo',
    'groupMgmt.description': 'Descripción',
    'groupMgmt.descriptionPlaceholder': 'Introduce la descripción del grupo',
    'groupMgmt.cancel': 'Cancelar',
    'groupMgmt.saveChanges': 'Guardar Cambios',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    // Update document language
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}