// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpwiblindzupzbwavump.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwd2libGluZHp1cHpid2F2dW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODM4ODcsImV4cCI6MjA3MDE1OTg4N30.6Ml3WifqwoxtL8HyxwyK20xRmN-Ov9JX9So2CuT06tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});